
package fr.afcepf.al33.conv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Convertisseur", targetNamespace = "http://conv.al33.afcepf.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Convertisseur {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "francToEuro", targetNamespace = "http://conv.al33.afcepf.fr/", className = "fr.afcepf.al33.conv.FrancToEuro")
    @ResponseWrapper(localName = "francToEuroResponse", targetNamespace = "http://conv.al33.afcepf.fr/", className = "fr.afcepf.al33.conv.FrancToEuroResponse")
    public double francToEuro(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @param cible
     * @param montant
     * @param source
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convertir", targetNamespace = "http://conv.al33.afcepf.fr/", className = "fr.afcepf.al33.conv.Convertir")
    @ResponseWrapper(localName = "convertirResponse", targetNamespace = "http://conv.al33.afcepf.fr/", className = "fr.afcepf.al33.conv.ConvertirResponse")
    public double convertir(
        @WebParam(name = "montant", targetNamespace = "")
        double montant,
        @WebParam(name = "source", targetNamespace = "")
        String source,
        @WebParam(name = "cible", targetNamespace = "")
        String cible);

    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "euroToFranc", targetNamespace = "http://conv.al33.afcepf.fr/", className = "fr.afcepf.al33.conv.EuroToFranc")
    @ResponseWrapper(localName = "euroToFrancResponse", targetNamespace = "http://conv.al33.afcepf.fr/", className = "fr.afcepf.al33.conv.EuroToFrancResponse")
    public double euroToFranc(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAuteur", targetNamespace = "http://conv.al33.afcepf.fr/", className = "fr.afcepf.al33.conv.GetAuteur")
    @ResponseWrapper(localName = "getAuteurResponse", targetNamespace = "http://conv.al33.afcepf.fr/", className = "fr.afcepf.al33.conv.GetAuteurResponse")
    public String getAuteur();

}
